# Header
menu:
  主页: /
  所有文章: /archives
  PHP: /categories/php
  前端: /categories/js
  Linux: /categories/linux
  随笔: /categories/essay
  阅读: /categories/read
# SubNav
subnav:
  github: "https://github.com/AhuiLi"
  #weibo: "#"
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/LiAhui"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
# google_analytics: ''
baidu_tongji: true
favicon: /favicon.ico

#你的头像url
avatar: /img/avatar.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true
arthurs: 3aeb3eb0f543f7cf8111f91b780e9995
#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: true
#开启——
#aboutme: ArthurLi，大一从网站制作开始，。。。。
